# Generated by Django 4.1.10 on 2023-08-03 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
